# Generated by Django 5.0.4 on 2024-04-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st_booking', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Active'), (2, 'Cancelled'), (3, 'Booked')], default=1),
        ),
    ]
