# Generated by Django 5.0.4 on 2024-04-26 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=150)),
                ('contact_number', models.CharField(blank=True, max_length=13, null=True)),
                ('booking_price_per_hour', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('lat', models.IntegerField()),
                ('long', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StadiumImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='images')),
                ('is_main', models.BooleanField(default=False)),
                ('stadium', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stadium.stadium')),
            ],
        ),
    ]
