# Generated by Django 5.0.4 on 2024-05-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadium', '0002_remove_stadium_long_stadium_lon_stadium_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stadium',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
